"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
format = """
[╭{owo} ](bold green)$username$directory$os$line_break$character"""

right_format = """$git_branch$git_state$git_status$cmd_duration$time"""

[character]
success_symbol = '[╰─>](bold green)'
error_symbol = '[x >](bold red)'

[git_branch]
format = '[ $symbol$branch]($style) '
style = 'cyan'

[directory]
format = "[](fg:#a3ca5c bg:none)[$path]($style)[ ](fg:#a3ca5c bg:none)"
style = "fg:#000000 bg:#a3ca5c"
truncate_to_repo=false

[username]
show_always = true

[time]
disabled = false

[cmd_duration]
format = "[](fg:#232323 bg:none)[$duration]($style)[ ](fg:#a3ca5c bg:#232323)[](fg:#000000 bg:#a3ca5c)[ ](fg:#a3ca5c bg:none)"
style = "fg:#e5e5e5 bg:#232323"
min_time = 0
disabled = false

[battery]
disabled = false

[os]
disabled = false

[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = ''
CentOS = ''
Debian = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Linux = ''
Macos = ''
Manjaro = ''
Mariner = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenCloudOS = ''
openEuler = ''
openSUSE = ''
OracleLinux = '⊂⊃'
Raspbian = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = ''
