theme = "default"
client_id = "317415dc7cb34148b374e1a5b11cc9c2"
client_port = 8080
login_redirect_uri = "http://127.0.0.1:8989/login"
playback_format = """
{status} {track} • {artists} {liked}
{album}
{metadata}"""
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
enable_streaming = "Never"
page_size_in_rows = 20
play_icon = "▶"
pause_icon = ""
liked_icon = "♥"
border_type = "Plain"
progress_bar_type = "Rectangle"
enable_media_control = true
enable_cover_image_cache = true
default_device = "vatn"
seek_duration_secs = 5
sort_artist_albums_by_type = false
cover_img_scale = 1.05

[layout]
playback_window_position = "Top"
playback_window_height = 6

[layout.library]
playlist_percent = 40
album_percent = 40

[device]
name = "eldur"
device_type = "computer"
volume = 100
bitrate = 320
audio_cache = false
normalization = false
autoplay = false
